[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "readii-idc-notebooks"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
