[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "readii-idc-notebooks"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"


[dependencies]
python = "3.10.*"
ipykernel = ">=6.29.5,<7"
pip = ">=23.3.2,<24"
python-dotenv = ">=1.0.1,<2"
joblib = ">=1.4.2,<2"

[pypi-dependencies]
project-lighter = { version = "==0.0.2a19" }
foundation-cancer-image-biomarker = ">=1.0, <2"

med-imagetools = { path = "../repos/med-imagetools", editable = true }
readii = { path = "../repos/readii", editable = true }
readii_idc_notebooks = { path = ".", editable = true }
